export const LISTING_LIST_REQUEST = "LISTING_LIST_REQUEST";
export const LISTING_LIST_SUCCESS = "LISTING_LIST_SUCCESS";
export const LISTING_LIST_FAIL = "LISTING_LIST_FAIL";

export const LISTING_CREATE_REQUEST = "LISTING_CREATE_REQUEST";
export const LISTING_CREATE_SUCCESS = "LISTING_CREATE_SUCCESS";
export const LISTING_CREATE_FAIL = "LISTING_CREATE_FAIL";
export const LISTING_CREATE_RESET = "LISTING_CREATE_RESET";

export const LISTING_DELETE_REQUEST = "LISTING_DELETE_REQUEST";
export const LISTING_DELETE_SUCCESS = "LISTING_DELETE_SUCCESS";
export const LISTING_DELETE_FAIL = "LISTING_DELETE_FAIL";
